### ISSUE TITLE
MongoError occurred when initialise new channel

### ISSUE THREAD

**Issue by leeyyi** [akohsa/BEAS#1]
Hi
I've configured the fabric and merged BEAS/fabric-samples with the target correctly.
But a mongoError occurred when I'm executing the command "node server.js" and I failed to initialise new channel.
Thanks.
The output:

> Wallet path: /home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/wallet
An identity for the admin user "admin" already exists in the wallet
Wallet path: /home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/wallet
An identity for the user "server" already exists in the wallet
Wallet path: /home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/wallet
Genesis Weight Block has been submitted to the Ledger!
/home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/node_modules/mongodb/lib/utils.js:668
          throw error;
          ^
MongoError: MongoClient must be connected before calling MongoClient.prototype.db
    at MongoClient.db (/home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/node_modules/mongodb/lib/mongo_client.js:314:11)
    at client.connect.err (/home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/server.js:171:41)
    at /home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/node_modules/mongodb/lib/utils.js:665:9
    at err (/home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/node_modules/mongodb/lib/mongo_client.js:224:23)
    at parseFn (/home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/node_modules/mongodb/lib/operations/connect.js:284:21)
    at QueryReqWrap.dns.resolveSrv [as callback] (/home/xxx/go/src/github.com/leeyyi/fabric-samples/BEAS/javascript/storageServer/node_modules/mongodb/lib/core/uri_parser.js:60:21)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:196:10)

**Comment by Hacker-Pet** [comment]
i have the same error, did you solve it?
